version: "2"
services:
  application:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: transaction-control-application
    container_name: "transaction-control-application"
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    container_name: "transactions-control-db"
    environment:
      - POSTGRES_PASSWORD=sql
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "./database-scripts/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql"
    ports:
      - 5432:5432