version: "3"
services:
  application:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: transaction-control-application
    container_name: "transaction-control-application"
    ports:
      - 8080:8080
    links:
      - database
  database:
    image: postgres
    container_name: "transactions-control-db"
    environment:
      - POSTGRES_PASSWORD=sql
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "./database-scripts/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql"
    ports:
      - 5432:5432